version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000  # For dev
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - AWS_REGION=us-east-1
      - BEDROCK_MODEL=anthropic.claude-v2
      - S3_BUCKET=your-bucket-name
    command: uvicorn local_api:app --host 0.0.0.0 --port 8000  # You can mock Lambda using FastAPI for dev
