AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10

Parameters:
  BucketName:
    Type: String
  MaxFileSizeMB:
    Type: Number
    Default: 10
  AllowedFileTypes:
    Type: String
    Default: image/jpeg,image/png,application/pdf

Resources:
  S3UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: src/upload_handler/ 
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          MAX_FILE_SIZE_MB: !Ref MaxFileSizeMB
          ALLOWED_FILE_TYPES: !Ref AllowedFileTypes
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /generate-upload-url
            Method: post

Outputs:
  UploadApiUrl:
    Description: "API Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-upload-url"
