AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10

Parameters:
  BucketName:
    Type: String
  MaxFileSizeMB:
    Type: Number
    Default: 10
  AllowedFileTypes:
    Type: String
    # Supported: PDF, DOCX, DOC, TXT, RTF, ODT
    Default: image/jpeg,image/png,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword,text/plain,application/rtf,application/vnd.oasis.opendocument.text

Resources:
  S3UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: src/upload_handler/ 
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          MAX_FILE_SIZE_MB: !Ref MaxFileSizeMB
          ALLOWED_FILE_TYPES: !Ref AllowedFileTypes
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /generate-upload-url
            Method: post
  ExtractTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/extract_loader/app.lambda_handler
      CodeUri: .
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
      Layers:
        # Tesseract OCR Lambda Layer (region-agnostic)
        - !Sub arn:aws:lambda:${AWS::Region}:764866452798:layer:tesseract-ocr:5
      Events:
        S3DocumentUpload:
          Type: S3
          Properties:
            Bucket: !Ref BucketName
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
                  - Name: suffix
                    Value: .pdf
                  - Name: suffix
                    Value: .docx
                  - Name: suffix
                    Value: .doc
                  - Name: suffix
                    Value: .txt
                  - Name: suffix
                    Value: .rtf
                  - Name: suffix
                    Value: .odt

Outputs:
  UploadApiUrl:
    Description: "API Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-upload-url"
